from .resources import (
    NLTK_LANG_MAP, SPACY_MODELS, SPACY_LANG_MAP, STOPWORDS_CACHE,
    DATA_API_DIR, DATA_CRAWLER_DIR, REPORTS_DIR, LOGGER
)

__all__ = [
    "NLTK_LANG_MAP",
    "SPACY_MODELS",
    "SPACY_LANG_MAP",
    "STOPWORDS_CACHE",
    "DATA_API_DIR",
    "DATA_CRAWLER_DIR",
    "REPORTS_DIR",
    "LOGGER"
]